### PR TITLE
Add More Signes = Warning Sign & Added K53 Sign Manual

### PR DESCRIPTION
**Pull request by JonathanAspeling**
Good day Shailen,

Added in more Warning Signs. Didn't do the full monty as yet.
Wanting to check in with you that this works, maby get some feedback and can then soldier on.

Added 12 New Signs.
Added 1 New PDF Doc that has some good data for the signs.
Added CSV file with File names, Sign Name, Purpose etc.

### CODE REVIEW

**Comment by JonathanAspeling** [comment]
This is my first time doing a pull request! Any teaching will be appreciated :D 
Followed this Youtube Video [https://www.youtube.com/watch?v=rgbCcBNZcdQ](url)

**Comment by shailen-naidoo** [comment]
Hey man! Thanks for all the effort, will check it out asap :)

**Comment by JonathanAspeling** [comment]
Awesome thanks a lot, Just wanting to verify whether the signs assets I've created are on par with what is needed - can then steamroll out more 👍

**Comment by shailen-naidoo** [comment]
Had a quick glance at your changes, so far congratulations on your first pull request :clap:

**Comment by JonathanAspeling** [comment]
Thanks S, Eager to get some more things on before Thursday so we can report on some movement on the Project during status updates. On the lookout for your final verdict.

**Comment by shailen-naidoo** [comment]
@JonathanAspeling Hey man! Had some more time to look at the files you added. I noticed that you added a `csv` file to the `warning-signs` folder. Do you mind removing that file for now as we want to store only images in the `images/*/**` folder :smile:

**Comment by JonathanAspeling** [comment]
100% Will do - Actually planning on Closing this pull request - Will then do a new PR with more assets some read me additions: (1) Mentioning the Slack Channel on ZATech (2) Mention the Trello Board (3) Spelling mistake 😄 and so forth

**Pull request closed without merging**
